extends Node

signal language_changed(language: String)

var language: String = "pt"

var _strings: Dictionary = {
	"pt": {
		"game.title": "Aura Farmer 6 7",
		"menu.play": "Jogar",
		"menu.achievements": "Conquistas",
		"menu.settings": "Configurações",
		"menu.quit": "Sair",
		"menu.tagline": "Clique, brilhe e ative o farm mais absurdo da academia vazia.",
		"ui.aura_current": "Aura Atual",
		"ui.aura_total": "Aura Total",
		"ui.aura_per_click": "Aura por Clique",
		"ui.aura_per_second": "Aura por Segundo",
		"ui.aura_level": "Nível da Aura",
		"ui.next_stage": "Próximo estágio",
		"ui.shop": "Loja",
		"ui.shop_subtitle": "Escolha entre clique, automação e drip espiritual.",
		"ui.all": "Tudo",
		"ui.settings": "Configurações",
		"ui.back": "Voltar",
		"ui.pause": "Pausado",
		"ui.resume": "Continuar jogando",
		"ui.exit_to_menu": "Sair para o menu",
		"ui.buy": "Comprar",
		"ui.level": "Nível",
		"ui.max_stage": "Forma final desbloqueada",
		"ui.prestige": "Renascer",
		"ui.essence": "Essência",
		"ui.essence_bonus": "{amount} | +{bonus}% bônus",
		"ui.essence_next": "{percent}% até {target}",
		"ui.essence_ready": "Pronto: +{amount}",
		"ui.prestige_hint": "Reinicia a Aura atual e concede bônus permanente.",
		"ui.offline_title": "Falsa produtividade detectada",
		"ui.offline_time": "Tempo fora: {time}",
		"ui.offline_body": "Enquanto você fingia responder mensagens importantes, o farm continuou brilhando.",
		"ui.close": "Fechar",
		"achievements.title": "Conquistas",
		"achievements.subtitle": "{unlocked}/{total} badges desbloqueados",
		"achievements.locked": "Badge bloqueado",
		"achievements.locked_hint": "Continue farmando Aura para revelar essa conquista.",
		"achievement.first_click.name": "Primeiro clique",
		"achievement.first_click.description": "Clique uma vez no personagem.",
		"achievement.ten_clicks.name": "Aquecimento",
		"achievement.ten_clicks.description": "Clique 10 vezes.",
		"achievement.hundred_clicks.name": "Dedo calibrado",
		"achievement.hundred_clicks.description": "Clique 100 vezes.",
		"achievement.thousand_clicks.name": "Cardio de dedo",
		"achievement.thousand_clicks.description": "Clique 1.000 vezes.",
		"achievement.first_aura.name": "Primeira faísca",
		"achievement.first_aura.description": "Ganhe sua primeira Aura.",
		"achievement.aura_100.name": "Brilho inicial",
		"achievement.aura_100.description": "Alcance 100 de Aura total.",
		"achievement.aura_1k.name": "Mil de respeito",
		"achievement.aura_1k.description": "Alcance 1K de Aura total.",
		"achievement.aura_10k.name": "Academia percebeu",
		"achievement.aura_10k.description": "Alcance 10K de Aura total.",
		"achievement.aura_100k.name": "Aura fazendo barulho",
		"achievement.aura_100k.description": "Alcance 100K de Aura total.",
		"achievement.aura_1m.name": "Milionário de Aura",
		"achievement.aura_1m.description": "Alcance 1M de Aura total.",
		"achievement.aura_10m.name": "Lenda local",
		"achievement.aura_10m.description": "Alcance 10M de Aura total.",
		"achievement.aura_100m.name": "Patrimônio espiritual",
		"achievement.aura_100m.description": "Alcance 100M de Aura total.",
		"achievement.aura_1b.name": "Bilionário do brilho",
		"achievement.aura_1b.description": "Alcance 1B de Aura total.",
		"achievement.aura_1t.name": "Trilhão absurdo",
		"achievement.aura_1t.description": "Alcance 1T de Aura total.",
		"achievement.first_upgrade.name": "Investidor espiritual",
		"achievement.first_upgrade.description": "Compre seu primeiro upgrade.",
		"achievement.five_upgrades.name": "Carrinho cheio",
		"achievement.five_upgrades.description": "Compre 5 níveis de upgrades.",
		"achievement.twenty_upgrades.name": "Cliente premium",
		"achievement.twenty_upgrades.description": "Compre 20 níveis de upgrades.",
		"achievement.upgrade_level_10.name": "Especialista",
		"achievement.upgrade_level_10.description": "Leve qualquer upgrade ao nível 10.",
		"achievement.upgrade_level_50.name": "Obsessão rentável",
		"achievement.upgrade_level_50.description": "Leve qualquer upgrade ao nível 50.",
		"achievement.click_build.name": "Build de clique",
		"achievement.click_build.description": "Compre 10 níveis em upgrades de clique.",
		"achievement.auto_farm.name": "Farm no automático",
		"achievement.auto_farm.description": "Produza Aura por segundo.",
		"achievement.auto_engine.name": "Motor de Aura",
		"achievement.auto_engine.description": "Produza 1K de Aura por segundo.",
		"achievement.multiplier_build.name": "Juros compostos",
		"achievement.multiplier_build.description": "Compre 5 níveis em multiplicadores.",
		"achievement.drip_dark_glasses.name": "Óculos da confiança",
		"achievement.drip_dark_glasses.description": "Compre os óculos escuros.",
		"achievement.legendary_skin.name": "Modo lendário",
		"achievement.legendary_skin.description": "Atinja a skin lendária.",
		"achievement.ancient_champion.name": "Campeão ancestral",
		"achievement.ancient_champion.description": "Desbloqueie a skin heroica.",
		"achievement.first_rebirth.name": "Primeiro renascimento",
		"achievement.first_rebirth.description": "Renasça uma vez e ganhe Essência.",
		"achievement.essence_25.name": "Essência concentrada",
		"achievement.essence_25.description": "Acumule 25 de Essência.",
		"achievement.cosmic_form.name": "Forma cósmica",
		"achievement.cosmic_form.description": "Leve a Aura para o espaço.",
		"achievement.platinum.name": "Platina 6 7",
		"achievement.platinum.description": "Desbloqueie todos os outros badges.",
		"settings.language": "Idioma",
		"settings.sfx_volume": "Volume dos efeitos",
		"settings.music_volume": "Volume da música",
		"settings.music_enabled": "Música ligada",
		"settings.fullscreen": "Tela cheia",
		"settings.volume": "Volume",
		"settings.reduced_motion": "Reduzir animações",
		"upgrade.category.click": "Power-up de Clique",
		"upgrade.category.auto": "Farm Automático",
		"upgrade.category.multiplier": "Multiplicador de Aura",
		"upgrade.effect.click": "+{value} Aura por clique",
		"upgrade.effect.auto": "+{value} Aura por segundo",
		"upgrade.effect.multiplier": "+{value}% multiplicador global",
		"upgrade.effect.flavor": "Efeito misterioso, provavelmente caro",
		"upgrade.fresh_cut.name": "Corte novo",
		"upgrade.fresh_cut.description": "O cabelo entendeu a missão antes do dono.",
		"upgrade.dark_glasses.name": "Óculos escuros",
		"upgrade.dark_glasses.description": "Protege os olhos do brilho da própria confiança.",
		"upgrade.gold_chain.name": "Corrente dourada",
		"upgrade.gold_chain.description": "Fisicamente pesada, emocionalmente inevitável.",
		"upgrade.expensive_sneakers.name": "Tênis caro",
		"upgrade.expensive_sneakers.description": "A sola custa mais que algumas decisões de vida.",
		"upgrade.oversized_hoodie.name": "Moletom oversized",
		"upgrade.oversized_hoodie.description": "Quanto maior o moletom, menor a necessidade de explicar.",
		"upgrade.gaming_laptop.name": "Notebook gamer",
		"upgrade.gaming_laptop.description": "A ventoinha gera 12% da Aura nacional.",
		"upgrade.premium_coffee.name": "Café premium",
		"upgrade.premium_coffee.description": "Notas de caramelo, planilhas e ansiedade elegante.",
		"upgrade.infinite_creatine.name": "Creatina infinita",
		"upgrade.infinite_creatine.description": "O scoop olha para você e pede descanso.",
		"upgrade.sigma_mode.name": "Sigma Mode",
		"upgrade.sigma_mode.description": "Silêncio dramático com retorno composto.",
		"upgrade.mysterious_energy.name": "Energia misteriosa",
		"upgrade.mysterious_energy.description": "Ninguém sabe de onde veio. Todos querem um link.",
		"upgrade.shorts_editor.name": "Editor de Shorts",
		"upgrade.shorts_editor.description": "Transforma três segundos de pose em patrimônio espiritual.",
		"upgrade.npc_admirers.name": "NPCs admiradores",
		"upgrade.npc_admirers.description": "Ficam em volta aplaudindo cada respiração rentável.",
		"upgrade.motivational_course.name": "Curso motivacional",
		"upgrade.motivational_course.description": "Sete módulos para aprender que dormir era opcional.",
		"upgrade.discipline.name": "Disciplina",
		"upgrade.discipline.description": "Acorda cedo, olha para o nada e chama isso de método.",
		"upgrade.mindset.name": "Mindset",
		"upgrade.mindset.description": "Quando o problema vira oportunidade, a Aura cobra taxa.",
		"upgrade.cosmic_aura_subscription.name": "Assinatura de Aura Cósmica",
		"upgrade.cosmic_aura_subscription.description": "Renova sozinha e ninguém sabe como cancelar.",
		"stage.normal.name": "Pessoa comum",
		"stage.normal.description": "Ainda paga boleto com expressão neutra.",
		"stage.small_glow.name": "Pequeno brilho",
		"stage.small_glow.description": "A iluminação começou a pedir cachê.",
		"stage.bright_eyes.name": "Olhos brilhando",
		"stage.bright_eyes.description": "Olhar de quem descobriu juros compostos.",
		"stage.blue_aura.name": "Aura azul",
		"stage.blue_aura.description": "A sala ficou um pouco mais anime.",
		"stage.gold_aura.name": "Aura dourada",
		"stage.gold_aura.description": "Agora o brilho tem contador de patrimônio.",
		"stage.tiny_thunder.name": "Pequenos raios",
		"stage.tiny_thunder.description": "Energia suficiente para assustar carregadores baratos.",
		"stage.golden_overdrive.name": "Modo Aura Dourada",
		"stage.golden_overdrive.description": "O cabelo virou energia e a academia pediu silêncio.",
		"stage.floating.name": "Flutuando",
		"stage.floating.description": "A gravidade pediu demissão.",
		"stage.energy_fragments.name": "Fragmentos orbitando",
		"stage.energy_fragments.description": "Pedrinhas de ego circulam em velocidade preocupante.",
		"stage.heroic_champion.name": "Campeão ancestral",
		"stage.heroic_champion.description": "Poder de desenho antigo, shape de propaganda proibida.",
		"stage.constellations.name": "Cosmic I",
		"stage.constellations.description": "O shape saiu da Terra, mas ainda responde boleto.",
		"stage.cosmic_2.name": "Cosmic II",
		"stage.cosmic_2.description": "A energia começou a mudar de cor sozinha.",
		"stage.cosmic_3.name": "Cosmic III",
		"stage.cosmic_3.description": "Fragmentos de ego ganharam órbita estável.",
		"stage.cosmic_4.name": "Cosmic IV",
		"stage.cosmic_4.description": "A aura ficou rosa e agressivamente rentável.",
		"stage.cosmic_500m.name": "Cosmic V: Meio Bilhão",
		"stage.cosmic_500m.description": "A transformação dourada que obriga o universo a olhar duas vezes.",
		"stage.cosmic_6.name": "Cosmic VI",
		"stage.cosmic_6.description": "A academia agora tem maré gravitacional.",
		"stage.cosmic_7.name": "Cosmic VII",
		"stage.cosmic_7.description": "Sete camadas de brilho e nenhuma explicação razoável.",
		"stage.cosmic_8.name": "Cosmic VIII",
		"stage.cosmic_8.description": "A realidade começou a render passivamente.",
		"stage.cosmic_9.name": "Cosmic IX",
		"stage.cosmic_9.description": "Última parada antes do absurdo bilionário.",
		"stage.scenario_shift.name": "Cenário alterado",
		"stage.scenario_shift.description": "As cores do mundo aceitaram a hierarquia.",
		"stage.cosmic_aura.name": "Aura cósmica",
		"stage.cosmic_aura.description": "A autoestima agora tem campo gravitacional.",
		"stage.tiny_black_holes.name": "Mini buracos negros",
		"stage.tiny_black_holes.description": "Sugam críticas construtivas e alguns móveis.",
		"stage.galaxy_orbit.name": "Galáxias orbitando",
		"stage.galaxy_orbit.description": "O universo está seguindo para mais dicas.",
		"stage.absurd_form.name": "Forma absurda",
		"stage.absurd_form.description": "A lenda ficou sem legenda."
	},
	"en": {
		"game.title": "Aura Farmer 6 7",
		"menu.play": "Play",
		"menu.achievements": "Achievements",
		"menu.settings": "Settings",
		"menu.quit": "Quit",
		"menu.tagline": "Click, glow, and activate the most absurd empty-gym farm.",
		"ui.aura_current": "Current Aura",
		"ui.aura_total": "Total Aura",
		"ui.aura_per_click": "Aura per Click",
		"ui.aura_per_second": "Aura per Second",
		"ui.aura_level": "Aura Level",
		"ui.next_stage": "Next Stage",
		"ui.shop": "Shop",
		"ui.shop_subtitle": "Choose between clicks, automation, and spiritual drip.",
		"ui.all": "All",
		"ui.settings": "Settings",
		"ui.back": "Back",
		"ui.pause": "Paused",
		"ui.resume": "Resume game",
		"ui.exit_to_menu": "Exit to menu",
		"ui.buy": "Buy",
		"ui.level": "Level",
		"ui.max_stage": "Final form unlocked",
		"ui.prestige": "Rebirth",
		"ui.essence": "Essence",
		"ui.essence_bonus": "{amount} | +{bonus}% bonus",
		"ui.essence_next": "{percent}% to {target}",
		"ui.essence_ready": "Ready: +{amount}",
		"ui.prestige_hint": "Resets current Aura and grants permanent bonus.",
		"ui.offline_title": "Fake productivity detected",
		"ui.offline_time": "Time away: {time}",
		"ui.offline_body": "While you pretended to answer important messages, the farm kept glowing.",
		"ui.close": "Close",
		"achievements.title": "Achievements",
		"achievements.subtitle": "{unlocked}/{total} badges unlocked",
		"achievements.locked": "Locked badge",
		"achievements.locked_hint": "Keep farming Aura to reveal this achievement.",
		"achievement.first_click.name": "First Click",
		"achievement.first_click.description": "Click the character once.",
		"achievement.ten_clicks.name": "Warm-Up",
		"achievement.ten_clicks.description": "Click 10 times.",
		"achievement.hundred_clicks.name": "Calibrated Finger",
		"achievement.hundred_clicks.description": "Click 100 times.",
		"achievement.thousand_clicks.name": "Finger Cardio",
		"achievement.thousand_clicks.description": "Click 1,000 times.",
		"achievement.first_aura.name": "First Spark",
		"achievement.first_aura.description": "Earn your first Aura.",
		"achievement.aura_100.name": "Early Glow",
		"achievement.aura_100.description": "Reach 100 total Aura.",
		"achievement.aura_1k.name": "One Thousand Respect",
		"achievement.aura_1k.description": "Reach 1K total Aura.",
		"achievement.aura_10k.name": "The Gym Noticed",
		"achievement.aura_10k.description": "Reach 10K total Aura.",
		"achievement.aura_100k.name": "Aura Making Noise",
		"achievement.aura_100k.description": "Reach 100K total Aura.",
		"achievement.aura_1m.name": "Aura Millionaire",
		"achievement.aura_1m.description": "Reach 1M total Aura.",
		"achievement.aura_10m.name": "Local Legend",
		"achievement.aura_10m.description": "Reach 10M total Aura.",
		"achievement.aura_100m.name": "Spiritual Net Worth",
		"achievement.aura_100m.description": "Reach 100M total Aura.",
		"achievement.aura_1b.name": "Glow Billionaire",
		"achievement.aura_1b.description": "Reach 1B total Aura.",
		"achievement.aura_1t.name": "Absurd Trillion",
		"achievement.aura_1t.description": "Reach 1T total Aura.",
		"achievement.first_upgrade.name": "Spiritual Investor",
		"achievement.first_upgrade.description": "Buy your first upgrade.",
		"achievement.five_upgrades.name": "Full Cart",
		"achievement.five_upgrades.description": "Buy 5 upgrade levels.",
		"achievement.twenty_upgrades.name": "Premium Customer",
		"achievement.twenty_upgrades.description": "Buy 20 upgrade levels.",
		"achievement.upgrade_level_10.name": "Specialist",
		"achievement.upgrade_level_10.description": "Raise any upgrade to level 10.",
		"achievement.upgrade_level_50.name": "Profitable Obsession",
		"achievement.upgrade_level_50.description": "Raise any upgrade to level 50.",
		"achievement.click_build.name": "Click Build",
		"achievement.click_build.description": "Buy 10 levels in click upgrades.",
		"achievement.auto_farm.name": "Automatic Farm",
		"achievement.auto_farm.description": "Produce Aura per second.",
		"achievement.auto_engine.name": "Aura Engine",
		"achievement.auto_engine.description": "Produce 1K Aura per second.",
		"achievement.multiplier_build.name": "Compound Interest",
		"achievement.multiplier_build.description": "Buy 5 levels in multipliers.",
		"achievement.drip_dark_glasses.name": "Confidence Glasses",
		"achievement.drip_dark_glasses.description": "Buy the dark glasses.",
		"achievement.legendary_skin.name": "Legendary Mode",
		"achievement.legendary_skin.description": "Reach the legendary skin.",
		"achievement.ancient_champion.name": "Ancient Champion",
		"achievement.ancient_champion.description": "Unlock the heroic skin.",
		"achievement.first_rebirth.name": "First Rebirth",
		"achievement.first_rebirth.description": "Rebirth once and earn Essence.",
		"achievement.essence_25.name": "Concentrated Essence",
		"achievement.essence_25.description": "Accumulate 25 Essence.",
		"achievement.cosmic_form.name": "Cosmic Form",
		"achievement.cosmic_form.description": "Take Aura into space.",
		"achievement.platinum.name": "Platinum 6 7",
		"achievement.platinum.description": "Unlock every other badge.",
		"settings.language": "Language",
		"settings.sfx_volume": "SFX volume",
		"settings.music_volume": "Music volume",
		"settings.music_enabled": "Music enabled",
		"settings.fullscreen": "Fullscreen",
		"settings.volume": "Volume",
		"settings.reduced_motion": "Reduced motion",
		"upgrade.category.click": "Click Power-up",
		"upgrade.category.auto": "Automatic Farming",
		"upgrade.category.multiplier": "Aura Multiplier",
		"upgrade.effect.click": "+{value} Aura per click",
		"upgrade.effect.auto": "+{value} Aura per second",
		"upgrade.effect.multiplier": "+{value}% global multiplier",
		"upgrade.effect.flavor": "Mysterious effect, probably expensive",
		"upgrade.fresh_cut.name": "Fresh Cut",
		"upgrade.fresh_cut.description": "The haircut understood the mission first.",
		"upgrade.dark_glasses.name": "Dark Glasses",
		"upgrade.dark_glasses.description": "Protects your eyes from your own confidence.",
		"upgrade.gold_chain.name": "Gold Chain",
		"upgrade.gold_chain.description": "Physically heavy, emotionally unavoidable.",
		"upgrade.expensive_sneakers.name": "Expensive Sneakers",
		"upgrade.expensive_sneakers.description": "The sole costs more than some life choices.",
		"upgrade.oversized_hoodie.name": "Oversized Hoodie",
		"upgrade.oversized_hoodie.description": "The bigger the hoodie, the fewer explanations needed.",
		"upgrade.gaming_laptop.name": "Gaming Laptop",
		"upgrade.gaming_laptop.description": "The fan generates 12% of national Aura.",
		"upgrade.premium_coffee.name": "Premium Coffee",
		"upgrade.premium_coffee.description": "Notes of caramel, spreadsheets, and polished anxiety.",
		"upgrade.infinite_creatine.name": "Infinite Creatine",
		"upgrade.infinite_creatine.description": "The scoop looks at you and asks for mercy.",
		"upgrade.sigma_mode.name": "Sigma Mode",
		"upgrade.sigma_mode.description": "Dramatic silence with compound returns.",
		"upgrade.mysterious_energy.name": "Mysterious Energy",
		"upgrade.mysterious_energy.description": "Nobody knows where it came from. Everyone wants a link.",
		"upgrade.shorts_editor.name": "Shorts Editor",
		"upgrade.shorts_editor.description": "Turns three seconds of posing into spiritual equity.",
		"upgrade.npc_admirers.name": "NPC Admirers",
		"upgrade.npc_admirers.description": "They stand around applauding every profitable breath.",
		"upgrade.motivational_course.name": "Motivational Course",
		"upgrade.motivational_course.description": "Seven modules to learn that sleep was optional.",
		"upgrade.discipline.name": "Discipline",
		"upgrade.discipline.description": "Wakes up early, stares into space, calls it a method.",
		"upgrade.mindset.name": "Mindset",
		"upgrade.mindset.description": "When the problem becomes an opportunity, Aura charges a fee.",
		"upgrade.cosmic_aura_subscription.name": "Cosmic Aura Subscription",
		"upgrade.cosmic_aura_subscription.description": "Renews by itself and nobody knows how to cancel.",
		"stage.normal.name": "Regular Person",
		"stage.normal.description": "Still pays bills with a neutral expression.",
		"stage.small_glow.name": "Tiny Glow",
		"stage.small_glow.description": "The lighting started asking for a fee.",
		"stage.bright_eyes.name": "Glowing Eyes",
		"stage.bright_eyes.description": "The look of someone who discovered compound interest.",
		"stage.blue_aura.name": "Blue Aura",
		"stage.blue_aura.description": "The room became slightly more anime.",
		"stage.gold_aura.name": "Golden Aura",
		"stage.gold_aura.description": "The glow now has a net-worth tracker.",
		"stage.tiny_thunder.name": "Tiny Thunder",
		"stage.tiny_thunder.description": "Enough energy to scare cheap chargers.",
		"stage.golden_overdrive.name": "Golden Aura Mode",
		"stage.golden_overdrive.description": "The hair became energy and the gym asked for silence.",
		"stage.floating.name": "Floating",
		"stage.floating.description": "Gravity handed in its notice.",
		"stage.energy_fragments.name": "Orbiting Fragments",
		"stage.energy_fragments.description": "Little ego stones circling at worrying speed.",
		"stage.heroic_champion.name": "Ancient Champion",
		"stage.heroic_champion.description": "Vintage cartoon power, forbidden-commercial physique.",
		"stage.constellations.name": "Cosmic I",
		"stage.constellations.description": "The physique left Earth, but still answers bills.",
		"stage.cosmic_2.name": "Cosmic II",
		"stage.cosmic_2.description": "The energy started changing colors by itself.",
		"stage.cosmic_3.name": "Cosmic III",
		"stage.cosmic_3.description": "Ego fragments achieved stable orbit.",
		"stage.cosmic_4.name": "Cosmic IV",
		"stage.cosmic_4.description": "The aura became pink and aggressively profitable.",
		"stage.cosmic_500m.name": "Cosmic V: Half Billion",
		"stage.cosmic_500m.description": "The golden transformation that forces the universe to look twice.",
		"stage.cosmic_6.name": "Cosmic VI",
		"stage.cosmic_6.description": "The gym now has gravitational tides.",
		"stage.cosmic_7.name": "Cosmic VII",
		"stage.cosmic_7.description": "Seven layers of glow and no reasonable explanation.",
		"stage.cosmic_8.name": "Cosmic VIII",
		"stage.cosmic_8.description": "Reality started earning passively.",
		"stage.cosmic_9.name": "Cosmic IX",
		"stage.cosmic_9.description": "Final stop before billionaire absurdity.",
		"stage.scenario_shift.name": "Shifted Scenery",
		"stage.scenario_shift.description": "The world's colors accepted the hierarchy.",
		"stage.cosmic_aura.name": "Cosmic Aura",
		"stage.cosmic_aura.description": "Self-esteem now has a gravity field.",
		"stage.tiny_black_holes.name": "Tiny Black Holes",
		"stage.tiny_black_holes.description": "They absorb constructive criticism and some furniture.",
		"stage.galaxy_orbit.name": "Orbiting Galaxies",
		"stage.galaxy_orbit.description": "The universe subscribed for more tips.",
		"stage.absurd_form.name": "Absurd Form",
		"stage.absurd_form.description": "The legend ran out of captions."
	}
}

func set_language(new_language: String) -> void:
	if not _strings.has(new_language):
		return
	language = new_language
	SettingsManager.set_setting("language", new_language)
	language_changed.emit(language)

func apply_language(new_language: String) -> void:
	if not _strings.has(new_language):
		return
	language = new_language
	language_changed.emit(language)

func t(key: String, values: Dictionary = {}) -> String:
	var language_strings: Dictionary = _strings[language] if _strings.has(language) else {}
	var fallback_strings: Dictionary = _strings["pt"]
	var text: String = str(language_strings.get(key, fallback_strings.get(key, key)))
	for token in values.keys():
		text = text.replace("{" + str(token) + "}", str(values[token]))
	return text
