extends RefCounted

static func get_stages() -> Array[Dictionary]:
	return [
		{"id": "normal", "threshold": 0.0, "name_key": "stage.normal.name", "description_key": "stage.normal.description", "primary_color": Color("#93a4b8"), "secondary_color": Color("#1f2937"), "particles": 0, "orbitals": 0, "float": false, "light_energy": 0.0, "character_scale": 0.72},
		{"id": "small_glow", "threshold": 100.0, "name_key": "stage.small_glow.name", "description_key": "stage.small_glow.description", "primary_color": Color("#8fffe1"), "secondary_color": Color("#164e63"), "particles": 6, "orbitals": 0, "float": false, "light_energy": 0.2, "character_scale": 0.76},
		{"id": "bright_eyes", "threshold": 500.0, "name_key": "stage.bright_eyes.name", "description_key": "stage.bright_eyes.description", "primary_color": Color("#fef08a"), "secondary_color": Color("#334155"), "particles": 10, "orbitals": 0, "float": false, "light_energy": 0.35, "character_scale": 0.8},
		{"id": "blue_aura", "threshold": 2000.0, "name_key": "stage.blue_aura.name", "description_key": "stage.blue_aura.description", "primary_color": Color("#60a5fa"), "secondary_color": Color("#172554"), "particles": 16, "orbitals": 1, "float": false, "light_energy": 0.45, "character_scale": 0.84},
		{"id": "gold_aura", "threshold": 10000.0, "name_key": "stage.gold_aura.name", "description_key": "stage.gold_aura.description", "primary_color": Color("#facc15"), "secondary_color": Color("#3f2f05"), "particles": 24, "orbitals": 2, "float": false, "light_energy": 0.6, "character_scale": 0.88},
		{"id": "tiny_thunder", "threshold": 100000.0, "name_key": "stage.tiny_thunder.name", "description_key": "stage.tiny_thunder.description", "primary_color": Color("#c084fc"), "secondary_color": Color("#2e1065"), "particles": 34, "orbitals": 3, "float": false, "light_energy": 0.75, "character_scale": 0.92},
		{"id": "golden_overdrive", "threshold": 500000.0, "name_key": "stage.golden_overdrive.name", "description_key": "stage.golden_overdrive.description", "primary_color": Color("#fde047"), "secondary_color": Color("#422006"), "particles": 42, "orbitals": 4, "float": false, "light_energy": 0.85, "character_scale": 0.94, "character_texture": "res://Assets/Sprites/Character/golden_overdrive_character.png"},
		{"id": "floating", "threshold": 1000000.0, "name_key": "stage.floating.name", "description_key": "stage.floating.description", "primary_color": Color("#22d3ee"), "secondary_color": Color("#083344"), "particles": 46, "orbitals": 4, "float": true, "light_energy": 0.9, "character_scale": 0.96, "character_texture": "res://Assets/Sprites/Character/legendary_character.png"},
		{"id": "heroic_champion", "threshold": 2000000.0, "name_key": "stage.heroic_champion.name", "description_key": "stage.heroic_champion.description", "primary_color": Color("#f97316"), "secondary_color": Color("#3b0764"), "particles": 54, "orbitals": 5, "float": true, "light_energy": 0.96, "character_scale": 0.98, "character_texture": "res://Assets/Sprites/Character/heroic_champion_character.png"},
		{"id": "energy_fragments", "threshold": 10000000.0, "name_key": "stage.energy_fragments.name", "description_key": "stage.energy_fragments.description", "primary_color": Color("#fb7185"), "secondary_color": Color("#4c0519"), "particles": 60, "orbitals": 6, "float": true, "light_energy": 1.0, "character_scale": 1.0, "character_texture": "res://Assets/Sprites/Character/legendary_drip_character.png"},
		{"id": "constellations", "threshold": 100000000.0, "name_key": "stage.constellations.name", "description_key": "stage.constellations.description", "primary_color": Color("#7dd3fc"), "secondary_color": Color("#082f49"), "particles": 80, "orbitals": 8, "float": true, "light_energy": 1.15, "character_scale": 1.04, "character_texture": "res://Assets/Sprites/Character/cosmic_1_character.png"},
		{"id": "cosmic_2", "threshold": 200000000.0, "name_key": "stage.cosmic_2.name", "description_key": "stage.cosmic_2.description", "primary_color": Color("#a78bfa"), "secondary_color": Color("#2e1065"), "particles": 86, "orbitals": 9, "float": true, "light_energy": 1.18, "character_scale": 1.045, "character_texture": "res://Assets/Sprites/Character/cosmic_2_character.png"},
		{"id": "cosmic_3", "threshold": 300000000.0, "name_key": "stage.cosmic_3.name", "description_key": "stage.cosmic_3.description", "primary_color": Color("#f0abfc"), "secondary_color": Color("#4a044e"), "particles": 92, "orbitals": 9, "float": true, "light_energy": 1.21, "character_scale": 1.05, "character_texture": "res://Assets/Sprites/Character/cosmic_3_character.png"},
		{"id": "cosmic_4", "threshold": 400000000.0, "name_key": "stage.cosmic_4.name", "description_key": "stage.cosmic_4.description", "primary_color": Color("#fb7185"), "secondary_color": Color("#4c0519"), "particles": 98, "orbitals": 10, "float": true, "light_energy": 1.24, "character_scale": 1.055, "character_texture": "res://Assets/Sprites/Character/cosmic_4_character.png"},
		{"id": "cosmic_500m", "threshold": 500000000.0, "name_key": "stage.cosmic_500m.name", "description_key": "stage.cosmic_500m.description", "primary_color": Color("#fde047"), "secondary_color": Color("#422006"), "particles": 128, "orbitals": 12, "float": true, "light_energy": 1.38, "character_scale": 1.07, "character_texture": "res://Assets/Sprites/Character/cosmic_500m_character.png"},
		{"id": "cosmic_6", "threshold": 600000000.0, "name_key": "stage.cosmic_6.name", "description_key": "stage.cosmic_6.description", "primary_color": Color("#5eead4"), "secondary_color": Color("#134e4a"), "particles": 116, "orbitals": 12, "float": true, "light_energy": 1.33, "character_scale": 1.075, "character_texture": "res://Assets/Sprites/Character/cosmic_6_character.png"},
		{"id": "cosmic_7", "threshold": 700000000.0, "name_key": "stage.cosmic_7.name", "description_key": "stage.cosmic_7.description", "primary_color": Color("#c4b5fd"), "secondary_color": Color("#312e81"), "particles": 122, "orbitals": 13, "float": true, "light_energy": 1.36, "character_scale": 1.08, "character_texture": "res://Assets/Sprites/Character/cosmic_7_character.png"},
		{"id": "cosmic_8", "threshold": 800000000.0, "name_key": "stage.cosmic_8.name", "description_key": "stage.cosmic_8.description", "primary_color": Color("#e879f9"), "secondary_color": Color("#581c87"), "particles": 128, "orbitals": 13, "float": true, "light_energy": 1.39, "character_scale": 1.085, "character_texture": "res://Assets/Sprites/Character/cosmic_8_character.png"},
		{"id": "cosmic_9", "threshold": 900000000.0, "name_key": "stage.cosmic_9.name", "description_key": "stage.cosmic_9.description", "primary_color": Color("#e5e7eb"), "secondary_color": Color("#111827"), "particles": 134, "orbitals": 14, "float": true, "light_energy": 1.42, "character_scale": 1.09, "character_texture": "res://Assets/Sprites/Character/cosmic_9_character.png"},
		{"id": "scenario_shift", "threshold": 1000000000.0, "name_key": "stage.scenario_shift.name", "description_key": "stage.scenario_shift.description", "primary_color": Color("#f9a8d4"), "secondary_color": Color("#500724"), "particles": 140, "orbitals": 15, "float": true, "light_energy": 1.45, "character_scale": 1.1, "character_texture": "res://Assets/Sprites/Character/cosmic_character.png"},
		{"id": "cosmic_aura", "threshold": 10000000000.0, "name_key": "stage.cosmic_aura.name", "description_key": "stage.cosmic_aura.description", "primary_color": Color("#818cf8"), "secondary_color": Color("#111827"), "particles": 130, "orbitals": 12, "float": true, "light_energy": 1.45, "character_scale": 1.12, "character_texture": "res://Assets/Sprites/Character/cosmic_character.png"},
		{"id": "tiny_black_holes", "threshold": 100000000000.0, "name_key": "stage.tiny_black_holes.name", "description_key": "stage.tiny_black_holes.description", "primary_color": Color("#e5e7eb"), "secondary_color": Color("#030712"), "particles": 160, "orbitals": 14, "float": true, "light_energy": 1.6, "character_scale": 1.16, "character_texture": "res://Assets/Sprites/Character/cosmic_character.png"},
		{"id": "galaxy_orbit", "threshold": 1000000000000.0, "name_key": "stage.galaxy_orbit.name", "description_key": "stage.galaxy_orbit.description", "primary_color": Color("#f0abfc"), "secondary_color": Color("#1e1b4b"), "particles": 200, "orbitals": 18, "float": true, "light_energy": 1.8, "character_scale": 1.2, "character_texture": "res://Assets/Sprites/Character/void_emperor_character.png"},
		{"id": "absurd_form", "threshold": 1000000000000000.0, "name_key": "stage.absurd_form.name", "description_key": "stage.absurd_form.description", "primary_color": Color("#ffffff"), "secondary_color": Color("#0f172a"), "particles": 260, "orbitals": 24, "float": true, "light_energy": 2.0, "character_scale": 1.24, "character_texture": "res://Assets/Sprites/Character/void_emperor_character.png"}
	]
